In [1]:
import pandas as pd
import numpy as np
import requests as re
import utils2 as ut

from io import BytesIO, StringIO
from zipfile import ZipFile

In [2]:
"""
_____________________________________________________________________________________________________________________________________________________________________________________________________

IGR - Índice Geral de Reclamações:

O Índice Geral de Reclamações (IGR) é uma métrica calculada pela ANS com base nas reclamações registradas por consumidores e que foram processadas via Notificação de Intermediação Preliminar (NIP).

Tal indicador foi desenvolvido com o objetivo de dar maior transparência às reivindicações registradas por consumidores junto aos canais de atendimento da ANS, 
funcionando como um termômetro da satisfação dos serviços prestados pelas operadoras de planos de saúde. 

Ele apresenta uma relação inversamente proporcional à satisfação dos beneficiários, vale dizer, que quanto menor o valor do IGR, maior é a satisfação dos beneficiários com a(s) Operadora(s).
_____________________________________________________________________________________________________________________________________________________________________________________________________

igr_geral = pd.read_csv(
    'https://dadosabertos.ans.gov.br/FTP/PDA/IGR/IGR_versao_2023/IGR.csv', 
    sep=';', 
    encoding='UTF-8')

igr_geral.to_csv('igr_geral.csv') # gera um arquivo .csv com o dataframe

1. Gera o arquivo com o código acima;
2. Lê o arquivo com a função read_csv() abaixo.

"""

ut.baixar_extrair_mesclar('https://dadosabertos.ans.gov.br/FTP/PDA/IGR/IGR_versao_2023/IGR.csv')

════════════════════════════════════════════════════════════════════════════════════════════════════════════
🚀 FASE   : inicialização
🔧 FUNÇÃO : baixar_extrair_mesclar
🧭 ETAPA  : Início do processamento
📂 CAMINHO: https://dadosabertos.ans.gov.br/FTP/PDA/IGR/IGR_versao_2023/IGR.csv
📄 ARQUIVO: IGR.csv
📊 STATUS : [░░░░░░░░░░░░░░░░░░░░░░░░░░] 0/0 (0.0%)
⏳ FALTAM : 0
════════════════════════════════════════════════════════════════════════════════════════════════════════════

════════════════════════════════════════════════════════════════════════════════════════════════════════════
🚀 FASE   : ingestão
🔧 FUNÇÃO : ingerir_origem
🧭 ETAPA  : Origem detectada: arquivo_tabular
📂 CAMINHO: https://dadosabertos.ans.gov.br/FTP/PDA/IGR/IGR_versao_2023/IGR.csv
📄 ARQUIVO: IGR.csv
📊 STATUS : [░░░░░░░░░░░░░░░░░░░░░░░░░░] 0/0 (0.0%)
⏳ FALTAM : 0
════════════════════════════════════════════════════════════════════════════════════════════════════════════

════════════════════════════════════════════════════════════════════════════════════════════════════════════
🧮 FASE   : planejamento
🔧 FUNÇÃO : definir_total_arquivos
🧭 ETAPA  : Total de arquivos planejado: https://dadosabertos.ans.gov.br/FTP/PDA/IGR/IGR_versao_2023/IGR.csv
📂 CAMINHO: c:\GIT\DadosANS\processamentos\IGR_20260324_014635
📄 ARQUIVO: 1 item(ns)
📊 STATUS : [░░░░░░░░░░░░░░░░░░░░░░░░░░] 0/1 (0.0%)
⏳ FALTAM : 1
════════════════════════════════════════════════════════════════════════════════════════════════════════════

════════════════════════════════════════════════════════════════════════════════════════════════════════════
🌐 FASE   : ingestão
🔧 FUNÇÃO : ingerir_arquivo_unico
🧭 ETAPA  : Baixando arquivo único
📂 CAMINHO: https://dadosabertos.ans.gov.br/FTP/PDA/IGR/IGR_versao_2023/IGR.csv
📄 ARQUIVO: IGR.csv
📊 STATUS : [░░░░░░░░░░░░░░░░░░░░░░░░░░] 0/1 (0.0%)
⏳ FALTAM : 1
════════════════════════════════════════════════════════════════════════════════════════════════════════════

════════════════════════════════════════════════════════════════════════════════════════════════════════════
✅ FASE   : ingestão
🔧 FUNÇÃO : ingerir_arquivo_unico
🧭 ETAPA  : Arquivo tabular ingerido com sucesso
📂 CAMINHO: c:\GIT\DadosANS\processamentos\IGR_20260324_014635\ingestao\downloads
📄 ARQUIVO: IGR.csv
📊 STATUS : [██████████████████████████] 1/1 (100.0%)
⏳ FALTAM : 0
════════════════════════════════════════════════════════════════════════════════════════════════════════════

════════════════════════════════════════════════════════════════════════════════════════════════════════════
🧮 FASE   : planejamento
🔧 FUNÇÃO : definir_total_arquivos
🧭 ETAPA  : Total de arquivos planejado: mesclagem incremental
📂 CAMINHO: c:\GIT\DadosANS\processamentos\IGR_20260324_014635
📄 ARQUIVO: 1 item(ns)
📊 STATUS : [░░░░░░░░░░░░░░░░░░░░░░░░░░] 0/1 (0.0%)
⏳ FALTAM : 1
════════════════════════════════════════════════════════════════════════════════════════════════════════════

════════════════════════════════════════════════════════════════════════════════════════════════════════════
ℹ️ FASE   : saída
🔧 FUNÇÃO : mesclar_arquivos_ingeridos
🧭 ETAPA  : Mesclagem não executada: apenas um arquivo compatível foi ingerido
📂 CAMINHO: c:\GIT\DadosANS\processamentos\IGR_20260324_014635\ingestao\downloads
📄 ARQUIVO: IGR.csv
📊 STATUS : [░░░░░░░░░░░░░░░░░░░░░░░░░░] 0/1 (0.0%)
⏳ FALTAM : 1
════════════════════════════════════════════════════════════════════════════════════════════════════════════

════════════════════════════════════════════════════════════════════════════════════════════════════════════
📌 COMANDOS PRONTOS PARA LEITURA DOS ARQUIVOS NO PANDAS
Cole os comandos abaixo no notebook:

# Arquivos originais baixados/gerados
df_origem_igr = pd.read_csv(r"c:\GIT\DadosANS\processamentos\IGR_20260324_014635\ingestao\downloads\IGR.csv", encoding="utf-8-sig", low_memory=False)
════════════════════════════════════════════════════════════════════════════════════════════════════════════

════════════════════════════════════════════════════════════════════════════════════════════════════════════
🏁 FASE   : finalização
🔧 FUNÇÃO : baixar_extrair_mesclar
🧭 ETAPA  : Processamento concluído com sucesso
📂 CAMINHO: c:\GIT\DadosANS\processamentos\IGR_20260324_014635
📄 ARQUIVO: resultado final
📊 STATUS : [░░░░░░░░░░░░░░░░░░░░░░░░░░] 0/1 (0.0%)
⏳ FALTAM : 1
════════════════════════════════════════════════════════════════════════════════════════════════════════════

{'conteudo_zip': None,
 'pasta_execucao': 'c:\\GIT\\DadosANS\\processamentos\\IGR_20260324_014635',
 'pasta_ingestao': 'c:\\GIT\\DadosANS\\processamentos\\IGR_20260324_014635\\ingestao',
 'manifesto_arquivos': 'c:\\GIT\\DadosANS\\processamentos\\IGR_20260324_014635\\manifesto_arquivos.csv',
 'arquivos_lidos': ['IGR.csv'],
 'arquivos_ignorados': [],
 'erros': [],
 'df_unificado': None}

In [5]:
"""
_____________________________________________________________________________________________________________________________________________________________________________________________________

VMFE - Valor Comercial da Mensalidade por Faixa Etária

O conjunto de dados abertos "Valor Comercial da Mensalidade por faixa etária" se refere aos dados informados nas Notas Técnicas homologadas junto à ANS em conformidade com o Anexo II-B, 
da IN/DIPRO Nº 8, de 27 de dezembro de 2002.

_____________________________________________________________________________________________________________________________________________________________________________________________________

Código:

baixar_extrair_arquivo_zip() - utilização de função personalizada para aglutinar os arquivos em um só;

vmfe_url = 'https://dadosabertos.ans.gov.br/FTP/PDA/nota_tecnica_ntrp_vcm_faixa_etaria/nota_tecnica_vcm_faixa_etaria.zip'
vmfe_resultado = ut.baixar_extrair_juntar_zip(vmfe_url)
vmfe_df = vmfe_resultado['df_unificado']
vmfe_df.to_csv('vmfe_df.csv') # Gera um .csv com o arquivo mesclado na mesma pasta deste notebook

1. Gera o arquivo com o código acima;
2. Lê o arquivo com a função read_csv() abaixo.

"""

vmfe_df = pd.read_csv('vmfe_df.csv')
vmfe_df

,Unnamed: 0,CD_OPERADORA,ID_PLANO,CD_NOTA,DT_NTRP,ID_ABRG,FAIXA_ETARIA,VL_COMERCIAL_MENSALIDADE,VL_DESP_ASSISTENCIAL,VCM_MINIMO,VCM_MAXIMO,DT_ATUALIZACAO,arquivo_origem
0,0,300926,1362640,42535,29/01/2004,REGIONALIZADA,59 anos ou mais,259.50,85.66,181.65,337.35,17/03/2026,NOTA_TECNICA_VCM_FAIXA_ETARIA_2004.csv
1,1,300926,1362640,42535,29/01/2004,REGIONALIZADA,00 a 18 anos,46.50,18.94,32.55,60.45,17/03/2026,NOTA_TECNICA_VCM_FAIXA_ETARIA_2004.csv
2,2,300926,1362640,42535,29/01/2004,REGIONALIZADA,19 a 23 anos,59.50,25.40,41.65,77.35,17/03/2026,NOTA_TECNICA_VCM_FAIXA_ETARIA_2004.csv
3,3,300926,1362640,42535,29/01/2004,REGIONALIZADA,24 a 28 anos,71.50,22.77,50.05,92.95,17/03/2026,NOTA_TECNICA_VCM_FAIXA_ETARIA_2004.csv
4,4,300926,1362640,42535,29/01/2004,REGIONALIZADA,29 a 33 anos,79.50,25.59,55.65,103.35,17/03/2026,NOTA_TECNICA_VCM_FAIXA_ETARIA_2004.csv
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3435607,3435607,344362,1435076,415199,16/03/2026,REGIONALIZADA,39 a 43 anos,1464.90,145.99,1025.43,1904.37,17/03/2026,NOTA_TECNICA_VCM_FAIXA_ETARIA_2026.csv
3435608,3435608,344362,1435076,415199,16/03/2026,REGIONALIZADA,44 a 48 anos,1904.22,153.55,1332.95,2475.49,17/03/2026,NOTA_TECNICA_VCM_FAIXA_ETARIA_2026.csv
3435609,3435609,344362,1435076,415199,16/03/2026,REGIONALIZADA,49 a 53 anos,2244.12,165.76,1570.88,2917.36,17/03/2026,NOTA_TECNICA_VCM_FAIXA_ETARIA_2026.csv
3435610,3435610,344362,1435076,415199,16/03/2026,REGIONALIZADA,54 a 58 anos,2872.47,189.69,2010.73,3734.21,17/03/2026,NOTA_TECNICA_VCM_FAIXA_ETARIA_2026.csv
3435611,3435611,344362,1435076,415199,16/03/2026,REGIONALIZADA,59 anos ou mais,4251.54,226.70,2976.08,5527.00,17/03/2026,NOTA_TECNICA_VCM_FAIXA_ETARIA_2026.csv

In [6]:
"""
_____________________________________________________________________________________________________________________________________________________________________________________________________

TR - Taxa de Resolutividade:

A Taxa de Resolutividade (TR) é uma métrica calculada pela ANS com base nas reclamações registradas por consumidores e que foram processadas via Notificação de Intermediação Preliminar (NIP), 
que é considerado um método extrajudicial de resolução de conflitos. A TR mede a capacidade de resolução das demandas objeto de NIP, sem a necessidade de abertura de processo administrativo. 

Assim sendo, um percentual elevado de finalização de demandas no âmbito da NIP indica que a Operadora tem maior capacidade de equacionar o indício de infração narrado pelo consumidor.
_____________________________________________________________________________________________________________________________________________________________________________________________________

tr = pd.read_csv(
    'https://dadosabertos.ans.gov.br/FTP/PDA/taxa_de_resolutividade/pda-048-taxa_de_resolutividade.csv', 
    sep=';', 
    encoding='UTF-8')
tr.to_csv('taxa_resolutividade.csv') # gera um arquivo .csv com o dataframe

1. Gera o arquivo com o código acima;
2. Lê o arquivo com a função read_csv() abaixo.

"""

tr = pd.read_csv('taxa_resolutividade.csv')
tr

,Unnamed: 0,CD_REGISTRO_ANS,NM_RAZAO_SOCIAL,TP_NATUREZA,VL_TR,NR_NUMERADOR,NR_DENOMINADOR,CD_COMPETENCIA,DT_ATUALIZACAO
0,0,350729,OPERADORA DE PLANOS PRIVADOS DE ASSISTENCIA A ...,Assistencial,"100,00",1,1,2019-10,2026-03-09
1,1,368849,MEDIPLAN ASSISTENCIAL LTDA,Assistencial,"100,00",8,8,2019-10,2026-03-09
2,2,368849,MEDIPLAN ASSISTENCIAL LTDA,Não Assistencial,"100,00",1,1,2019-10,2026-03-09
3,3,325074,GREEN LINE SISTEMA DE SAÚDE S.A,Assistencial,"94,85",184,194,2019-10,2026-03-09
4,4,325074,GREEN LINE SISTEMA DE SAÚDE S.A,Não Assistencial,"88,37",38,43,2019-10,2026-03-09
...,...,...,...,...,...,...,...,...,...
63361,63361,352586,SISTEMAS E PLANOS DE SAÚDE LTDA.,Geral,"100,00",2,2,2015-01,2026-03-09
63362,63362,303623,CENTRO TRASMONTANO DE SAO PAULO,Geral,"70,97",22,31,2015-01,2026-03-09
63363,63363,400190,SANTO ANDRÉ PLANOS DE ASSISTENCIA MÉDICA LTDA.,Geral,"65,52",19,29,2015-01,2026-03-09
63364,63364,342611,ECONOMUS INSTITUTO DE SEGURIDADE SOCIAL,Geral,"87,50",7,8,2015-01,2026-03-09
63365,63365,337871,UNIMED RIO BRANCO COOPERATIVA DE TRABALHO MEDI...,Geral,"50,00",1,2,2015-01,2026-03-09

In [ ]:
"""
_____________________________________________________________________________________________________________________________________________________________________________________________________

PPH - Produtos e Prestadores Hospitalares:
    
Trata-se de conjunto de dados abertos que contém informações sobre a Rede de atendimento hospitalar ou urgência/emergência por plano de saúde: 
Listagem da rede de atendimento hospitalar ou urgência/emergência por plano de saúde e operadora.

_____________________________________________________________________________________________________________________________________________________________________________________________________
    
pph_url = 'https://dadosabertos.ans.gov.br/FTP/PDA/produtos_e_prestadores_hospitalares/produtos_e_prestadores_hospitalares.zip'
pph_resultado = ut.baixar_extrair_juntar_zip(pph_url)
pph_df = pph_resultado['df_unificado']
pph_df.to_csv('produtos_prestadores_hospitalares.csv') # Gera um .csv com o arquivo mesclado na mesma pasta deste notebook

1. Gera o arquivo com o código acima (o arquivo completo totaliza 1.6 Gb);
2. Lê o arquivo com a função read_csv() abaixo.

"""

pph = pd.read_csv('produtos_prestadores_hospitalares.csv')
pph

C:\Users\C124510\AppData\Local\Temp\ipykernel_19608\571230155.py:21: DtypeWarning: Columns (0: CD_PLANO) have mixed types. Specify dtype option on import or set low_memory=False.
  pph = pd.read_csv('produtos_prestadores_hospitalares.csv')

,Unnamed: 0,ID_REDE,CD_OPERADORA,NO_RAZAO,GR_MODALIDADE,DE_PORTE,ID_PLANO,CD_PLANO,TP_VIGENCIA_PLANO,CONTRATACAO,...,DE_TIPO_CONTRATO,DE_DISPONIBILIDADE,CD_MUNICIPIO,NM_MUNICIPIO,SG_UF,DT_VINCULO_INICIO,DT_VINCULO_FIM,NM_REGIAO,DT_ATUALIZACAO,arquivo_origem
0,0,16790920 227380852,515,ALLIANZ SAUDE S A,Seguradora,SEM BENEFICIARIOS,16790920,479118175,P,COLETIVO,...,Indireto,Parcial,120040,RIO BRANCO,AC,2017-09-26,NaN,NORTE,2026-02-24,produtos_prestadores_hospitalares_AC.csv
1,1,18919622 233880099,582,PORTO SEGURO SEGURO SAUDE S A,Seguradora,SEM BENEFICIARIOS,18919622,505567259,P,COLETIVO,...,Indireto,Parcial,120040,RIO BRANCO,AC,2025-10-14,NaN,NORTE,2026-02-24,produtos_prestadores_hospitalares_AC.csv
2,2,18919642 233880099,582,PORTO SEGURO SEGURO SAUDE S A,Seguradora,SEM BENEFICIARIOS,18919642,505569255,P,COLETIVO,...,Indireto,Parcial,120040,RIO BRANCO,AC,2025-10-14,NaN,NORTE,2026-02-24,produtos_prestadores_hospitalares_AC.csv
3,3,18893886 233880099,582,PORTO SEGURO SEGURO SAUDE S A,Seguradora,SEM BENEFICIARIOS,18893886,504679253,P,COLETIVO,...,Indireto,Parcial,120040,RIO BRANCO,AC,2025-08-12,NaN,NORTE,2026-02-24,produtos_prestadores_hospitalares_AC.csv
4,4,18880751 233880099,582,PORTO SEGURO SEGURO SAUDE S A,Seguradora,SEM BENEFICIARIOS,18880751,504266256,P,COLETIVO,...,Indireto,Parcial,120040,RIO BRANCO,AC,2025-07-08,NaN,NORTE,2026-02-24,produtos_prestadores_hospitalares_AC.csv
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23918272,23918272,18469630 237995244,421715,BRADESCO SAUDE OPERADORA DE PLANOS S A,Medicina de Grupo,SEM BENEFICIARIOS,18469630,491547220,P,COLETIVO,...,Direto,Parcial,172100,PALMAS,TO,2022-02-24,NaN,NORTE,2026-02-24,produtos_prestadores_hospitalares_TO.csv
23918273,23918273,18879234 258431842,421928,ALICE OPERADORA LTDA.,Medicina de Grupo,SEM BENEFICIARIOS,18879234,504235256,P,COLETIVO,...,Indireto,Total,172100,PALMAS,TO,2025-07-02,NaN,NORTE,2026-02-24,produtos_prestadores_hospitalares_TO.csv
23918274,23918274,18750673 266923062,422720,AMPLA PLANOS DE SAUDE LTDA,Medicina de Grupo,SEM BENEFICIARIOS,18750673,499281244,P,COLETIVO,...,Indireto,Parcial,172100,PALMAS,TO,2024-06-18,NaN,NORTE,2026-02-24,produtos_prestadores_hospitalares_TO.csv
23918275,23918275,18750542 266923049,422720,AMPLA PLANOS DE SAUDE LTDA,Medicina de Grupo,SEM BENEFICIARIOS,18750542,499275240,P,COLETIVO,...,Indireto,Parcial,172100,PALMAS,TO,2024-06-18,NaN,NORTE,2026-02-24,produtos_prestadores_hospitalares_TO.csv
23918276,23918276,18744969 260619664,423173,INTEGRA ASSISTENCIA MEDICA SA,Medicina de Grupo,SEM BENEFICIARIOS,18744969,499114241,P,COLETIVO,...,Indireto,Parcial,172100,PALMAS,TO,2024-06-06,NaN,NORTE,2026-02-24,produtos_prestadores_hospitalares_TO.csv

In [ ]:
"""
_____________________________________________________________________________________________________________________________________________________________________________________________________

RPC - Dados_Comunicados de Reajustes de Planos em Contratos Coletivos:

O banco de dados dos comunicados de reajuste dos contratos coletivos (RPC) é alimentado constantemente pelas operadoras mediante a aplicação dos reajustes de seus contratos e dentro dos prazos determinados,
conforme a norma em vigor. A IN/DIPRO nº 13, de 21 de julho de 2006, trata dos procedimentos de comunicação dos reajustes de planos coletivos à ANS e determina os prazos para envio destes comunicados, 
definindo os trimestres de envio como ocorrendo de: (1) março a maio, (2) junho a agosto, (3) setembro a novembro e (4) dezembro a fevereiro O prazo limite para envio dos comunicados de cada trimestre é o último dia do mês seguinte à conclusão do trimestre.

_____________________________________________________________________________________________________________________________________________________________________________________________________

rpc_url = 'https://dadosabertos.ans.gov.br/FTP/PDA/RPC/'
rpc_resultado = ut.baixar_extrair_juntar(rpc_url)
rpc_df = rpc_resultado['df_unificado']
rpc_df.to_csv('reajuste_contratos_coletivos.csv') # Gera um .csv com o arquivo mesclado na mesma pasta deste notebook

"""

rpc_df = pd.read_csv('reajuste_contratos_coletivos.csv')
rpc_df

,Unnamed: 0,ID_PLANO,ID_CONTRATO,CD_OPERADORA,DT_INIC_APLICACAO,DT_FIM_APLICACAO,QT_BENEF_COMUNICADO,PC_PERCENTUAL,DT_PROTOCOLO,NM_PROTOCOLO,LG_FATOR_MODERADOR,LG_ADESAO,LG_PARCELADO,LG_NEGOCIACAO,SG_UF_CONTRATO_REAJ,CD_AGRUPAMENTO,DT_CARGA,arquivo_origem
0,0,1482797,6BEBAC0AA4916BB3F377D5500EAE4261,336319,2005-01-01,2005-12-01,63,"39,62",2005-02-16,3839970426801070490,0,0,0,0,PE,0,2024-01-19,pda-043-rpc-2005_2009.csv
1,1,1482916,6A715AD9A9A570260FE0D63A45A054C3,327689,2005-01-01,2005-12-01,1,"11,75",2009-02-19,398634622443266820368,0,0,0,0,AL,0,2024-01-19,pda-043-rpc-2005_2009.csv
2,2,1482916,32B0BB9042C98BB1018D4AC7F33AC4AE,327689,2005-01-01,2005-12-01,1,"11,75",2009-02-19,398634622443266820368,0,0,0,0,AL,0,2024-01-19,pda-043-rpc-2005_2009.csv
3,3,1482916,46589D050B282E90054CCAE1FF6A9769,327689,2005-01-01,2005-12-01,1,"11,75",2009-02-19,398634622443266820368,0,0,0,0,AL,0,2024-01-19,pda-043-rpc-2005_2009.csv
4,4,1482916,A59E48752EAA2FCC6833A8083C70A08B,327689,2005-01-01,2005-12-01,1,"11,75",2009-02-19,398634622443266820368,0,0,0,0,AL,0,2024-01-19,pda-043-rpc-2005_2009.csv
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35978025,35978025,18491139,B3DC29FAE38969DA9BDE2576938798C0,326305,2025-08-01,2026-07-01,2,"15,98",2025-09-26,459266380733538908324,0,0,0,0,SP,1,2025-10-01,pda-043-rpc-202508.csv
35978026,35978026,18491139,81FD5CFF9A49F57FF9761600B2B166EE,326305,2025-08-01,2026-07-01,2,"15,98",2025-09-26,459266380733538908324,0,0,0,0,RJ,1,2025-10-01,pda-043-rpc-202508.csv
35978027,35978027,18491139,E655920B01FD0C8046817F941F234D0D,326305,2025-08-01,2026-07-01,5,"15,98",2025-09-26,459266380733538908324,0,0,0,0,DF,1,2025-10-01,pda-043-rpc-202508.csv
35978028,35978028,18491139,96C0EE7552F78E5054EF1A442DFEA477,326305,2025-08-01,2026-07-01,3,"15,98",2025-09-26,459266380733538908324,0,0,0,0,SP,1,2025-10-01,pda-043-rpc-202508.csv
35978029,35978029,18491139,F526CBF92AE7DF2A99EF58E9AF188C68,326305,2025-08-01,2026-07-01,2,"15,98",2025-09-26,459266380733538908324,0,0,0,0,RJ,1,2025-10-01,pda-043-rpc-202508.csv

In [ ]:
"""
_____________________________________________________________________________________________________________________________________________________________________________________________________

PHR - Procedimentos Hospitalares Realizados

Trata-se de um conjunto de dados abertos contendo uma Lista de procedimentos realizados em ambiente hospitalar pelos estabelecimentos que prestam serviço às operadoras de planos de saúde, 
por UF e mês e ano de competência.
_____________________________________________________________________________________________________________________________________________________________________________________________________

Este dataset é formado por inumeras pastas e arquivos, as quais ao final do processamento da função terão dezenas de milhões de registros, em razão disso, a função pode levar muitas horas para completar o processamento.

Dessa forma, orienta-se a utilização da versão "Big Data" da solução, a qual poderá ser executada em um ambiente Databricks.

# Baixa, extrai, junta e gera arquivos com os dfs (processamento demorado); 

phr_url = 'https://dadosabertos.ans.gov.br/FTP/PDA/TISS/HOSPITALAR/'
phr_resultado = ut.baixar_extrair_juntar(phr_url)

"""
# Baixa os arquivos com os dicionários de termos utilizados no df

ut.baixar_arquivo(
    'https://dadosabertos.ans.gov.br/FTP/PDA/TISS/DICIONARIO/Dicionario_de_variaveis_a_partir_de_2023.ods')
ut.baixar_arquivo(
    'https://dadosabertos.ans.gov.br/FTP/PDA/TISS/DICIONARIO/Dicionario_de_variaveis_ate_2022.ods')

KeyboardInterrupt: